mydata = read.table("household_power_consumption.txt", header=T, sep=";")
mydata$Date2 <- as.Date(as.character(mydata$Date), "%d/%m/%Y")
date1 <- as.Date(c("2007-02-01"))
date2 <- as.Date(c("2007-02-02"))
mydataCut <- subset(mydata, Date2 %in% c(date1, date2))
png(filename="plot3.png", width = 480, height = 480, units = "px")
mydataCut$dateTime <- strptime(paste(mydataCut$Date, mydataCut$Time, sep=","), format="%d/%m/%Y,%H:%M:%S")
mydataCut$DateTimeAsDate <- as.POSIXlt(mydataCut$dateTime)
with(mydataCut, plot(mydataCut$DateTimeAsDate, as.numeric(mydataCut$Sub_metering_1), type = "l", xlab = "", ylab = "Energy sub metering", col="black"))
with(mydataCut, points(mydataCut$DateTimeAsDate, as.numeric(mydataCut$Sub_metering_2), type = "l", col="red"))
with(mydataCut, points(mydataCut$DateTimeAsDate, as.numeric(mydataCut$Sub_metering_3), type = "l", col="blue"))
legend("topright", pch='-', col = c("black","red", "blue"), legend = c("Sub_Metering_1", "Sub_Metering_2", "Sub_Metering_3"))
dev.off()
